import React from 'react';
import {
  Crown,
  Trophy,
  Medal,
  Flame,
  DollarSign,
  TrendingUp,
  TrendingDown,
  Sparkles,
  Bot,
  Cpu,
  Image,
  Code,
  Megaphone,
  Mic,
  Zap,
  BookOpen,
  RefreshCw,
  Briefcase,
  GraduationCap,
  Smile,
  CheckCircle2,
  ExternalLink,
  ShieldCheck,
  Search,
  LayoutGrid,
  ChevronRight,
  ChevronDown,
  ArrowUpRight,
  Check,
  Plus,
  ArrowRight,
  Lock,
  Share2,
  Copy,
  Info,
  Radio,
  Eye,
  MousePointerClick,
  Sparkle
} from 'lucide-react';

export const CategoryIcon: React.FC<{ name?: string; className?: string }> = ({ name = '', className = 'w-4 h-4' }) => {
  const map: Record<string, React.FC<{ className?: string }>> = {
    'Bot': Bot,
    'Cpu': Cpu,
    'Image': Image,
    'Code': Code,
    'Megaphone': Megaphone,
    'Mic': Mic,
    'Zap': Zap,
    'BookOpen': BookOpen,
    'RefreshCw': RefreshCw,
    'Briefcase': Briefcase,
    'GraduationCap': GraduationCap,
    'Smile': Smile,
  };

  const IconComponent = map[name] || Sparkles;
  return <IconComponent className={className} />;
};

export {
  Crown,
  Trophy,
  Medal,
  Flame,
  DollarSign,
  TrendingUp,
  TrendingDown,
  Sparkles,
  CheckCircle2,
  ExternalLink,
  ShieldCheck,
  Search,
  LayoutGrid,
  ChevronRight,
  ChevronDown,
  ArrowUpRight,
  Check,
  Plus,
  ArrowRight,
  Lock,
  Share2,
  Copy,
  Info,
  Radio,
  Eye,
  MousePointerClick,
  Sparkle
};
